Repository tensorlayer/tensorlayer, pull requests merged in 2018-05, with the labels that each got.

#546 Update more.rst
  docs/user/more.rst
Labels: documentation

#575 TL.Files ambiguous test fixed generating a deprecation warning
  CHANGELOG.md
  tensorlayer/files.py
Labels: deprecation

#574 Issue #498 - Deprecation Warning Fix in `tl.layers.RNNLayer` with `inspect`
  CHANGELOG.md
  tensorlayer/layers/recurrent.py
Labels: deprecation

#573 Unittest for Deformable Convolution Added + Issue Fix #572
  .github/stale.yml
  CHANGELOG.md
  Dangerfile
  requirements_tf_cpu.txt
  requirements_tf_gpu.txt
  setup.py
  tensorlayer/layers/convolution.py
  tests/test_layers_convolution.py
Labels: bug

#579 Add a new layer ElementwiseLambdaLayer
  CHANGELOG.md
  docs/modules/layers.rst
  tensorlayer/layers/merge.py
  tests/test_layers_merge.py
Labels: enhancement, feature_request

#580 `tl.alphas` and `tl.alphas_like` added following the tf.ones/zeros and tf.zeros_like/ones_like
  CHANGELOG.md
  docs/index.rst
  docs/modules/array_ops.rst
  tensorlayer/__init__.py
  tensorlayer/array_ops.py
  tests/test_array_ops.py
Labels: discussion, feature_request

#566 Update utils.py and Create test_utils_predict.py
  CHANGELOG.md
  tensorlayer/utils.py
  tests/test_utils_predict.py
Labels: bug

#633 ReadTheDocs Links Updated & Version added on index page
  CHANGELOG.md
  README.md
  docs/index.rst
Labels: documentation

#636 AMSGrad optimizer added - Issue #583
  CHANGELOG.md
  docs/index.rst
  docs/modules/optimizers.rst
  tensorlayer/__init__.py
  tensorlayer/optimizers/__init__.py
  tensorlayer/optimizers/amsgrad.py
  tests/test_optimizer_amsgrad.py
Labels: enhancement, feature_request

#644 TF Build Matrix added for Travis
  .github/changelog.yml
  .travis.yml
  CHANGELOG.md
  README.md
  tensorlayer/__init__.py
Labels: CI_Tool, tensorflow

#648 Docker Integration
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile.gpu
  README.md
  docker/DockerLint.bat
  docker/pypi_list.py
  docker/python2/cpu/Dockerfile
  docker/python2/gpu/Dockerfile
  docker/python3/cpu/Dockerfile
  docker/python3/gpu/Dockerfile
  docker/version_prefix.py
Labels: CI_Tool, docker

#650 Error fix for Docker builds on master branch. Duplicate Job not ignored
  .circleci/config.yml
Labels: CI_Tool, bug, docker

#657 Tl.files refactored
  .pyup.yml
  .travis.yml
  CHANGELOG.md
  docker/python2/cpu/Dockerfile
  docker/python2/gpu/Dockerfile
  docker/python3/cpu/Dockerfile
  docker/python3/gpu/Dockerfile
  requirements/requirements.txt
  requirements/requirements_db.txt
  requirements/requirements_dev.txt
  requirements/requirements_doc.txt
  requirements/requirements_extra.txt
  requirements/requirements_test.txt
  requirements/requirements_tf_cpu.txt
  requirements/requirements_tf_gpu.txt
  setup.py
  tensorlayer/files/__init__.py
  tensorlayer/files/dataset_loaders/__init__.py
  tensorlayer/files/dataset_loaders/celebA_dataset.py
  tensorlayer/files/dataset_loaders/cifar10_dataset.py
  tensorlayer/files/dataset_loaders/cyclegan_dataset.py
  tensorlayer/files/dataset_loaders/flickr_1M_dataset.py
  tensorlayer/files/dataset_loaders/flickr_25k_dataset.py
  tensorlayer/files/dataset_loaders/imdb_dataset.py
  tensorlayer/files/dataset_loaders/matt_mahoney_dataset.py
  tensorlayer/files/dataset_loaders/mnist_dataset.py
  tensorlayer/files/dataset_loaders/mnist_fashion_dataset.py
  tensorlayer/files/dataset_loaders/mnist_utils.py
  tensorlayer/files/dataset_loaders/mpii_dataset.py
  tensorlayer/files/dataset_loaders/nietzsche_dataset.py
  tensorlayer/files/dataset_loaders/ptb_dataset.py
  tensorlayer/files/dataset_loaders/voc_dataset.py
  tensorlayer/files/dataset_loaders/wmt_en_fr_dataset.py
  tensorlayer/files/utils.py
  tensorlayer/layers/__init__.py
  tensorlayer/layers/binary.py
  tensorlayer/layers/convolution.py
  tensorlayer/layers/core.py
  tensorlayer/layers/extend.py
  tensorlayer/layers/flow_control.py
  tensorlayer/layers/importer.py
  tensorlayer/layers/merge.py
  tensorlayer/layers/normalization.py
  tensorlayer/layers/object_detection.py
  tensorlayer/layers/padding.py
  tensorlayer/layers/pooling.py
  tensorlayer/layers/recurrent.py
  tensorlayer/layers/shape.py
  tensorlayer/layers/spatial_transformer.py
  tensorlayer/layers/special_activation.py
  tensorlayer/layers/stack.py
  tensorlayer/layers/super_resolution.py
  tensorlayer/layers/time_distribution.py
  tensorlayer/models/mobilenetv1.py
  tensorlayer/models/squeezenetv1.py
  tensorlayer/models/vgg16.py
  tensorlayer/visualize.py
Labels: bug, enhancement, refactoring

#639 Refactoring Markdown Files
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  README.rst
  example/README.md
  setup.py
Labels: discussion, enhancement

#663 RTD Compilation Fix
  tensorlayer/__init__.py
Labels: CI_Tool, documentation
