Repository tensorlayer/tensorlayer, pull requests merged in 2018-06, with the labels that each got.

#635 Tutorial fixing
  CHANGELOG.md
  example/tutorial_cifar10_tfrecord.py
  example/tutorial_frozenlake_dqn.py
  example/tutorial_generate_text.py
  example/tutorial_inceptionV3_tfslim.py
  example/tutorial_mobilenet.py
  example/tutorial_ptb_lstm.py
  example/tutorial_ptb_lstm_state_is_tuple.py
  example/tutorial_squeezenet.py
  example/tutorial_tfrecord.py
  example/tutorial_tfrecord2.py
  example/tutorial_tfrecord3.py
  example/tutorial_vgg16.py
  example/tutorial_vgg19.py
  example/tutorial_word2vec_basic.py
Labels: bug, help_wanted

#672 Requirements Updated + RTD Build Fix
  .readthedocs.yml
  requirements/requirements_extra.txt
Labels: bug, documentation

#676 Update recurrent.py
  CHANGELOG.md
  tensorlayer/layers/recurrent.py
Labels: awaiting_response, bug

#662 Issue #642 - Add `AtrousDeConv2dLayer`
  .circleci/config.yml
  CHANGELOG.md
  README.md
  README.rst
  docs/modules/layers.rst
  example/tutorial_binarynet_cifar10_tfrecord.py
  example/tutorial_cifar10_tfrecord.py
  example/tutorial_dorefanet_cifar10_tfrecord.py
  example/tutorial_inceptionV3_tfslim.py
  example/tutorial_ptb_lstm.py
  example/tutorial_ptb_lstm_state_is_tuple.py
  example/tutorial_ternaryweight_cifar10_tfrecord.py
  example/tutorial_vgg19.py
  tensorlayer/__init__.py
  tensorlayer/cost.py
  tensorlayer/layers/binary.py
  tensorlayer/layers/convolution.py
  tensorlayer/layers/core.py
  tensorlayer/layers/extend.py
  tensorlayer/layers/flow_control.py
  tensorlayer/layers/inputs.py
  tensorlayer/layers/normalization.py
  tensorlayer/layers/object_detection.py
  tensorlayer/layers/recurrent.py
  tensorlayer/layers/special_activation.py
  tensorlayer/rein.py
  tests/test_layers_convolution.py
Labels: enhancement, feature_request

#687 ReLU6 rework
  CHANGELOG.md
  docs/modules/activation.rst
  docs/modules/layers.rst
  tensorlayer/activation.py
  tensorlayer/cost.py
  tensorlayer/layers/padding.py
  tensorlayer/layers/special_activation.py
  tests/test_activations.py
Labels: enhancement, feature_request

#692 Layer API Refactoring
  CHANGELOG.md
  example/tutorial_imagenet_inceptionV3_distributed.py
  tensorlayer/__init__.py
  tensorlayer/cost.py
  tensorlayer/db.py
  tensorlayer/files/dataset_loaders/imdb_dataset.py
  tensorlayer/files/dataset_loaders/voc_dataset.py
  tensorlayer/files/utils.py
  tensorlayer/initializers.py
  tensorlayer/iterate.py
  tensorlayer/layers/__init__.py
  tensorlayer/layers/binary.py
  tensorlayer/layers/convolution.py
  tensorlayer/layers/convolution/__init__.py
  tensorlayer/layers/convolution/atrous_conv.py
  tensorlayer/layers/convolution/binary_conv.py
  tensorlayer/layers/convolution/deformable_conv.py
  tensorlayer/layers/convolution/depthwise_conv.py
  tensorlayer/layers/convolution/dorefa_conv.py
  tensorlayer/layers/convolution/expert_conv.py
  tensorlayer/layers/convolution/expert_deconv.py
  tensorlayer/layers/convolution/group_conv.py
  tensorlayer/layers/convolution/separable_conv.py
  tensorlayer/layers/convolution/simplified_conv.py
  tensorlayer/layers/convolution/simplified_deconv.py
  tensorlayer/layers/convolution/ternary_conv.py
  tensorlayer/layers/core.py
  tensorlayer/layers/dense/__init__.py
  tensorlayer/layers/dense/base_dense.py
  tensorlayer/layers/dense/binary_dense.py
  tensorlayer/layers/dense/dorefa_dense.py
  tensorlayer/layers/dense/dropconnect.py
  tensorlayer/layers/dense/ternary_dense.py
  tensorlayer/layers/dropout.py
  tensorlayer/layers/extend.py
  tensorlayer/layers/flow_control.py
  tensorlayer/layers/image_resize.py
  tensorlayer/layers/importer.py
  tensorlayer/layers/inputs.py
  tensorlayer/layers/merge.py
  tensorlayer/layers/noise.py
  tensorlayer/layers/padding.py
  tensorlayer/layers/pooling.py
  tensorlayer/layers/reconstruction.py
  tensorlayer/layers/recurrent.py
  tensorlayer/layers/shape.py
  tensorlayer/layers/spatial_transformer.py
  tensorlayer/layers/stack.py
  tensorlayer/layers/super_resolution.py
  tensorlayer/layers/time_distribution.py
  tensorlayer/layers/utils.py
  tensorlayer/nlp.py
  tensorlayer/prepro.py
  tensorlayer/rein.py
  tensorlayer/utils.py
Labels: enhancement, refactoring

#691 Issue #689 fix - documentation refactoring
  .travis.yml
  CHANGELOG.md
  README.md
  README.rst
  docs/index.rst
  docs/modules/distributed.rst
  docs/modules/layers.rst
  docs/user/contributing.rst
  docs/user/example.rst
  docs/user/faq.rst
  docs/user/get_involved.rst
  docs/user/installation.rst
  docs/user/tutorial.rst
  example/tutorial_generate_text.py
  example/tutorial_inceptionV3_tfslim.py
  example/tutorial_mnist.py
  example/tutorial_mobilenet.py
  example/tutorial_ptb_lstm.py
  example/tutorial_ptb_lstm_state_is_tuple.py
  example/tutorial_squeezenet.py
  example/tutorial_vgg16.py
  example/tutorial_vgg19.py
  requirements/requirements.txt
  setup.py
  tensorlayer/__init__.py
  tensorlayer/activation.py
  tensorlayer/cost.py
  tensorlayer/decorators/__init__.py
  tensorlayer/decorators/deprecated.py
  tensorlayer/decorators/deprecated_alias.py
  tensorlayer/layers/__init__.py
  tensorlayer/layers/activation.py
  tensorlayer/layers/convolution/__init__.py
  tensorlayer/layers/convolution/super_resolution.py
  tensorlayer/layers/image_resampling.py
  tensorlayer/layers/importer.py
  tensorlayer/layers/lambda_layers.py
  tensorlayer/layers/merge.py
  tensorlayer/layers/normalization.py
  tensorlayer/layers/object_detection.py
  tensorlayer/layers/quantize.py
  tensorlayer/layers/recurrent.py
  tensorlayer/layers/scale.py
  tensorlayer/layers/utils.py
  tensorlayer/visualize.py
  tests/test_layers_activation.py
Labels: documentation, enhancement

#698 VGG19 Implementation with example
  CHANGELOG.md
  docs/modules/models.rst
  example/tutorial_models_vgg19.py
  tensorlayer/models/__init__.py
  tensorlayer/models/vgg19.py
Labels: enhancement, student_work
